{% set name = "smodels" %}
{% set version = "3.0.2" %}
# Python 3.7 enforced by pyhf requirement
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smodels-{{ version }}.tar.gz
  sha256: f584e1bcbb04e96f4ad31c4f74694c0725e347c9d6ca887350a47c8a1af3782a
  patches:
    - add-build-system.patch
    - add-python_requires.patch

build:
  entry_points:
    - smodels-config=smodels.installation:main
    - runSModelS.py=smodels.tools.runSModelS:main
    - smodelsTools.py=smodels.tools.smodelsTools:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docutils >=0.3
    - numpy >=1.18.0,!=1.21.*
    - scipy >=1.0.0
    - unum >=4.0.0
    - requests >=2.0.0
    - pyslha >=3.1.0
    - pyhf >=0.6.1
    - jsonpatch >=1.25
    - jsonschema >=3.2.0

test:
  imports:
    - smodels
  commands:
    - pip check

    - smodels-config --help
    - runSModelS.py --help
    - smodelsTools.py --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://smodels.github.io/
  summary: A tool for interpreting simplified-model results from the LHC
  license: GPL-3.0-or-later
  license_file: smodels/COPYING
  dev_url: https://github.com/SModelS/smodels/
  doc_url: http://smodels.github.io/

extra:
  recipe-maintainers:
    - matthewfeickert
